---
# handlers file for common

- name: config | Configuring rsyslog
  template:
    src: "90-graylog.conf.j2"
    dest: "/etc/rsyslog.d/90-graylog.conf"
    owner: "root"
    group: "root"
    mode: 0644
    backup: yes
  # notify:
  #   - 'restart {{ rsyslog_handler }}'
  when: ansible_os_family == "Debian"

- name: restart snmpd
  service:
    name: "rsyslog"
    state: restarted
